import { render, screen, fireEvent } from '@testing-library/react';
import { AIOutputCard } from './ai-output-card';
import { AIOutput } from '../App';
import React from 'react';
import { describe, test, expect } from 'vitest';

// 1. Create a mock output with a full explanantion object
const mockOutput: AIOutput = {
    id: '1',
    question: 'What is the capital of France?',
    text: 'The capital of France is Paris.',
    confidence: 99,
    timestamp: '2022-01-01T00:00:00Z',
    category: 'Geography',
    references: [],
    explanation: {
        agreement_pct: 100,
        model_a_final_score: 99,
        model_b_final_score: 99,
        reason: 'This is a test explanation generated by the backend.'
    },
    comparisonSummary: 'Summary',
    userFeedback: null,
};

describe('AIOutputCard Component', () => {

    test('renders the explanation correctly in the Evidence Analysis section', () => {
        // 2. Render the component
        render(
            <AIOutputCard
                output={mockOutput}
                viewMode='educational'
                onFeedbackChange={() => { }}
                onReferenceRating={() => { }}
            />
        );

        // 3. Open the collapsible section
        const showButton = screen.getByText(/Show References/i);
        fireEvent.click(showButton);

        // 4. Check if the "Evidence Analysis" header exists
        expect(screen.getByText('Evidence Analysis')).toBeInTheDocument();

        // 5. Check if the specific explanation text is displayed
        expect(screen.getByText('This is a test explanation generated by the backend.')).toBeInTheDocument();
    });

    test('handles missing explanation gracefully', () => {
        // Create a mock output with NO explanation
        const outputNoExplanation = { ...mockOutput, explanation: null };

        render(
            <AIOutputCard
                output={outputNoExplanation}
                viewMode='educational'
                onFeedbackChange={() => { }}
                onReferenceRating={() => { }}
            />
        )

        // Open the section
        const showButton = screen.getByText(/Show References/i);
        fireEvent.click(showButton);

        // Verify fallback text appears
        expect(screen.getByText('No explanation available.')).toBeInTheDocument();

    })
})