# Generated by Django 4.2.17 on 2025-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_query', models.TextField()),
                ('model_a', models.CharField(max_length=100)),
                ('model_b', models.CharField(max_length=100)),
                ('embed_model', models.CharField(max_length=100)),
                ('model_a_confidence', models.FloatField()),
                ('model_b_confidence', models.FloatField()),
                ('agreement_score', models.FloatField()),
                ('final_confidence', models.IntegerField()),
                ('best_model', models.CharField(max_length=100)),
                ('best_answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
