# Generated by Django 4.2.17 on 2025-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesponselog",
            name="brier",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airesponselog",
            name="ece",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airesponselog",
            name="geom_mean_conf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airesponselog",
            name="nll",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airesponselog",
            name="no_prob",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airesponselog",
            name="raw_blob_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="airesponselog",
            name="yes_prob",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
