# Generated by Django 4.2.17 on 2025-11-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_airesponselog_brier_airesponselog_ece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponselog',
            name='brier',
        ),
        migrations.RemoveField(
            model_name='airesponselog',
            name='ece',
        ),
        migrations.RemoveField(
            model_name='airesponselog',
            name='geom_mean_conf',
        ),
        migrations.RemoveField(
            model_name='airesponselog',
            name='nll',
        ),
        migrations.RemoveField(
            model_name='airesponselog',
            name='no_prob',
        ),
        migrations.RemoveField(
            model_name='airesponselog',
            name='raw_blob_id',
        ),
        migrations.RemoveField(
            model_name='airesponselog',
            name='yes_prob',
        ),
    ]
