# Generated by Django 4.2.17 on 2025-11-02 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("llm", "0002_airesponselog_brier_airesponselog_ece_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="airesponselog", name="brier",),
        migrations.RemoveField(model_name="airesponselog", name="ece",),
        migrations.RemoveField(model_name="airesponselog", name="geom_mean_conf",),
        migrations.RemoveField(model_name="airesponselog", name="nll",),
        migrations.RemoveField(model_name="airesponselog", name="no_prob",),
        migrations.RemoveField(model_name="airesponselog", name="raw_blob_id",),
        migrations.RemoveField(model_name="airesponselog", name="yes_prob",),
        migrations.CreateModel(
            name="ExportAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API path used", max_length=128),
                ),
                (
                    "dataset",
                    models.CharField(help_text="Logical dataset name", max_length=128),
                ),
                ("params", models.JSONField(help_text="Parameters used to export")),
                ("file_format", models.CharField(max_length=16)),
                ("filename", models.CharField(blank=True, max_length=256)),
                ("status", models.CharField(default="success", max_length=16)),
                ("message", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who triggered the export",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
